version: '3.8'

services:
  postgres-test:
    image: postgres:15-alpine
    container_name: studiohub-postgres-test
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_template
    ports:
      - "5433:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    command: >
      postgres
      -c max_connections=200
      -c shared_preload_libraries=pg_stat_statements
      -c log_statement=all
      -c log_duration=on
      -c log_min_duration_statement=0
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user -d test_template"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_test_data: